In [2]:
pip install opencv-python

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 MB 10.0 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: pip3.11 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2
import numpy as np

In [3]:
imagen= cv2.imread("lines.jpeg")

In [11]:
#Vemos la imagen y le pones el titulo de titulo Lineas al prompt 
cv2.imshow("Lineas", imagen)
print(cv2.waitKey(0))
cv2.destroyAllWindows()
for i in range(2):
    cv2.waitKey(1)

32


In [7]:
#Obtener los edges 
escala_gris= cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)
bordes =  cv2.Canny(escala_gris,75,150)

In [8]:
#Vemos la imagen y le pones el titulo de titulo Lineas_Detectadas al prompt 
cv2.imshow("Bordes", bordes)
print(cv2.waitKey(0))
cv2.destroyAllWindows()
for i in range(2):
    cv2.waitKey(1)

32


In [17]:
#Houghlines 

arreglo_lineas_Hough= cv2.HoughLinesP(bordes,1, np.pi/180, 30)
#CV2.Houghlines puede aceptar maxLineGap para zonas donde no hay lineas. Valores de 100, 200, 250 etc
#Hacer mas pequeño el threshold a un valor mas pequeño puede ayudar a una deteccion mejor de las lineas. 


print(arreglo_lineas_Hough[0:3])   #vemos como que regresa un arreglo y mostramos solo los primeros 3 valores

[[[115 408 115  18]]

 [[258 407 258  15]]

 [[ 23 414  23  18]]]


In [18]:
for i in arreglo_lineas_Hough:
    x1,y1,x2,y2 = i[0] #Tomamos cero porque vamos a tomar el array dentro del array 
    cv2.line(imagen, (x1,y1), (x2, y2), (0,0,255), 3) #Tomamos la imagen original y tomamos el primer punto x1&y1 y el segundo punto x2y2

In [19]:
 #Vemos la imagen y le pones el titulo de titulo Lineas al prompt 
cv2.imshow("Lineas", imagen)
print(cv2.waitKey(0))
cv2.destroyAllWindows()
for i in range(2):
    cv2.waitKey(1)

32


: 